extrinsic_calibration_by_hand:
  ros__parameters:
    image_topic: /image_raw
    lidar_topic: /livox/lidar
    debug_topic: /extrinsic_debug_image
    roi_x_min: -20.000000
    roi_x_max: 29.000000
    roi_y_min: -20.000000
    roi_y_max: 32.000000
    roi_z_min: -2.000000
    roi_z_max: 9.500000
    voxel_size: 0.120000
    decay_time: 0.400000
    post_merge_voxel_size: 0.150000
    max_projected_points: 12000
    draw_point_radius: 5
    profile_timing: true
